### PR TITLE
[WIP] Add more wait methods

### PR DESCRIPTION
**Pull request by aks-**
- waitNotPresent
- waitNotDisplayed
- waitTextExists
- waitTextEqual
- waitTextNotEqual
- waitAttributeEqual
- dragDrop

### CODE REVIEW

**Comment by aks-** [comment]
@grawk Oho tests failing. A lot of silly mistakes I made, found them while fixing tests. I will take a jab at it when I get up

**Comment by grawk** [comment]
OK. Looking through these PRs now.

**Comment by grawk** [comment]
It looks like this is more or less the same PR as #8? Can you consolidate into either this PR or that one and close the extraneous one? Thanks!

**Comment by aks-** [comment]
Okay, I removed the tests branch entirely. Also closed the issue I opened with regarding to that branch. I am still not sure why are we not using standard promises or bluebird?

**Comment by aredridel** [comment]
Oh, I can speak to the promises: Because `selenium-webdriver` provides its own, and it's really hard to participate in that project.

**Comment by nikulkarni** [comment]
@aks- Like @aredridel said selenium-webdriver uses its own promise manager and therefore we should use the same promises within nemo echo system. This way the co-ordination of webdriver commands is consistent. Also this PR is open for long, are you planning to update it?

**Comment by aks-** [comment]
@nikulkarni sorry been away, will have a look soon

**Comment by zzhengjian** [comment]
Hi, @aks- are you still planning to fix this?
@grawk @nikulkarni Can we send another PR for this, since the functions are quite useful.

**Comment by aks-** [comment]
Project doesn't seem alive anymore. I'm going to close this

**Pull request closed without merging**
